---
extends:
- stylelint-config-recommended-scss
- stylelint-config-css-modules

rules:
  at-rule-no-unknown:
  - true
  - ignoreAtRules:
    - each
    - else
    - error
    - function
    - if
    - include
    - mixin
    - return

  indentation: 2
  property-no-unknown: null
